### ISSUE TITLE
Somethings broken

### ISSUE THREAD

**Issue by hamuraiisam** [Cale-Torino/Takcar#2]
Hey, I'm using the latest FTS version. I have everything set up, the traccar API works fine ( checked, it delivers connected client positions ) and I get test point COT in atak, When I press test service button, nothing is happening in the console, I get a POTUS cot in my notification bar on the EUD but it's not place on the map, neither are any of traccar clients sent to the server.

I'd appreciate any advice. Thanks.

**Comment by hamuraiisam** [comment]
![image](https://user-images.githubusercontent.com/100773116/156357999-1015d16e-06cd-4e80-b97b-0a6199854adb.png)

**Comment by hamuraiisam** [comment]
![image](https://user-images.githubusercontent.com/100773116/156358133-fc740fe6-6cbb-4a39-a969-8c0ec703ca3b.png)

**Comment by hamuraiisam** [comment]
![image](https://user-images.githubusercontent.com/100773116/156358291-77e89d24-0bf9-4105-a201-957b3e97da33.png)

**Comment by hamuraiisam** [comment]
I've also tried running on chrome and firefox and different computers. no luck.

**Comment by hamuraiisam** [comment]
I tried with 1.0.0.4 and it is working

**Comment by Cale-Torino** [comment]
The `Traccar` test token is correct and the `FreeTAKServer` returns a valid GUID which means it did send the request successfully. However the test button uses the `FreeTAKServer` API If the request is not showing on `ATAK-CIV` or `WINTAK-CIV` then you may have to test the `FreeTAKServer` API separately first on your system to determine if there are any hiccups. `1.0.0.5` is working on my setup but I am using `FreeTAKServer` `1.9.7` as my testing server.
